name: AW Media
favicon: null
layout_spectrum: 0.5232975
typography_spectrum: 0.7939068
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: AW Media Group
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#171720'
    - '#886E5C'
    - '#FFFFFF'
    - '#E97F01'
    - '#01FFFF'
  brandStrength: 1
  lightness: 0.02057765168137848
  saturation: 0.09861013549380004
  rhythmicContrast: 0.765479524852708
purpose: []
