name: AW Media
favicon: null
layout_spectrum: 0.5561378030106425
typography_spectrum: 0.45460282219573855
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8752778603229672
  lightness: 0.020577651681378484
  saturation: 0.09861013549380004
  rhythmicContrast: 0.765479524852708
purpose: []
